services:
  migrations:
    build: .
    command: bash init.sh
    environment:
      - DB_URL=postgresql+asyncpg://postgres:72ZGBYhaq+vLjzWtUatsKw==@db:5432/postgres-bootcamp
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    command: runuser -u uvicorn -- /venv/bin/uvicorn src.main:app --app-dir /build --host 0.0.0.0 --port 8010 --workers 2 --loop uvloop
    environment:
      - DB_URL=postgresql+asyncpg://postgres:72ZGBYhaq+vLjzWtUatsKw==@db:5432/postgres-bootcamp
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "8010:8010"
    restart: always

  bot:
    build: .
    command: runuser -u uvicorn -- /venv/bin/python bot/main.py
    environment:
      - DB_URL=postgresql+asyncpg://postgres:72ZGBYhaq+vLjzWtUatsKw==@db:5432/postgres-bootcamp
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=72ZGBYhaq+vLjzWtUatsKw==
      - POSTGRES_DB=postgres-bootcamp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: