services:
  app:
    build: .
    restart: always
    environment:
      - DB_URL=postgresql+asyncpg://postgres:72ZGBYhaq+vLjzWtUatsKw==@db:5439/postgres-bootcamp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8010:8010"

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5439:5439"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=72ZGBYhaq+vLjzWtUatsKw==
      - POSTGRES_DB=postgres-bootcamp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  dbdata6: