services:
  app:
    build: .
    restart: always
    environment:
      - DB_URL=postgresql+asyncpg://postgres:72ZGBYhaq+vLjzWtUatsKw==@db:5432/postgres-bootcamp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8010:8010"

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=72ZGBYhaq+vLjzWtUatsKw==
      - POSTGRES_DB=postgres-bootcamp
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata:
  dbdata6:
