"""add match table

Revision ID: b1f130aba27b
Revises: 38a010ca8987
Create Date: 2025-04-18 15:51:20.345327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f130aba27b'
down_revision: Union[str, None] = '38a010ca8987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('cleanliness_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sleep_habits', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rent_budget', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('smoking_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pet_preference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pet_preference')
    op.drop_column('users', 'smoking_preference')
    op.drop_column('users', 'location')
    op.drop_column('users', 'rent_budget')
    op.drop_column('users', 'sleep_habits')
    op.drop_column('users', 'cleanliness_level')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
